### ISSUE TITLE
Plugin not loading

### ISSUE THREAD

**Issue by guidoferreyra** [mekkablue/ShowItalic#1]
Hi mekkablue I'm having the same issue as in your last plugin "Show tops and bottoms". :(
By the way I've created a similar plugin a few weeks ago :) Show Next Font.

Best regards.

```
Traceback (most recent call last):
  File "/Users/guidoferreyra/Library/Application Support/Glyphs/Plugins/ShowItalic.glyphsReporter/Contents/Resources/__boot__.py", line 47, in <module>
    _run('ShowItalic.py')
  File "/Users/guidoferreyra/Library/Application Support/Glyphs/Plugins/ShowItalic.glyphsReporter/Contents/Resources/__boot__.py", line 45, in _run
    execfile(path, globals(), globals())
  File "/Users/guidoferreyra/Library/Application Support/Glyphs/Plugins/ShowItalic.glyphsReporter/Contents/Resources/ShowItalic.py", line 6, in <module>
    class ShowItalic(ReporterPluginItalic):
objc.BadPrototypeError: Objective-C expects 1 arguments, Python argument has 2 arguments for <unbound selector drawBackground of ShowItalic at 0x10be508d0>
```

**Comment by mekkablue** [comment]
Both plugins have been written with new SDK templates. I still cannot reproduce the problem. Can you paste this in your Macro window, run it, and tell me what the output is?

```
import sys, os, math
from AppKit import *
print "-- System: %s" % sys.version
print "-- OS: %s; %s" % ( os.name, os.uname() )
for infoKey in ("CFBundleShortVersionString", "CFBundleVersion"):
    print "-- App %s: %s" % ( infoKey, NSBundle.bundleForClass_(GSMenu).infoDictionary().objectForKey_(infoKey) ) 
```

**Comment by guidoferreyra** [comment]
Of course, here the output.

```
-- System: 2.7.10 (default, Aug 22 2015, 20:33:39) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1)]
-- OS: posix; ('Darwin', 'iMac-de-Apple.local', '15.0.0', 'Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64', 'x86_64')
-- App CFBundleShortVersionString: 2.2.2
-- App CFBundleVersion: 826
```

By the way, where can I read about the new SDK?

**Comment by guidoferreyra** [comment]
Hey mekka I think I found a solution I did a fresh install of Glyphs and the problem was solved. Both Show Italic and STAB are working now. I restored my scripts and plugins folder and the issue was caused by Touché plugin.

Best regards.

**Comment by mekkablue** [comment]
The solution was removing the Touché plugin?

**Comment by guidoferreyra** [comment]
Yes, but I did a fresh install of the app and later I've installed the
plugins one by one until I found that Touché was causing the error.

**Comment by twardoch** [comment]
@mekkablue This just happened to me when I had Python 2.7.13 installed via Homebrew, and then "pyobjc" installed there via pip. It seems that the new PyObjC is not compatible with the one that ships with Sierra. I've uninstalled that PyObjC, and then added these lines to `~/Library/Python/2.7/lib/python/site-packages/sitecustomize.py`: 

```python
import site
site.addsitedir('/usr/local/lib/python2.7/site-packages')
site.addsitedir('/Library/Python/2.7/site-packages')
site.addsitedir('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python')
site.addsitedir('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC')
```

Now it's working.
