### ISSUE TITLE
The script does not show glyphs made of components

### ISSUE THREAD

**Issue by designiq** [mekkablue/ShowItalic#2]
It would be great to show glyphs made of components. It would make comparing placement of diacritics much easier and faster in Regular and Italic styles. Thanks!

**Comment by mekkablue** [comment]
It works in 2.2.2, but not in the latest 2.3 beta anymore. I’m investigating why.

**Comment by mekkablue** [comment]
I think I fixed it. Can you try, and close the issue if it works for you too?
