### ISSUE TITLE
Upright masters only shows the first Italic master

### ISSUE THREAD

**Issue by clauseggers** [mekkablue/ShowItalic#7]
The upright masters only shows the first Italic master

<img width="429" alt="Screenshot 2024-04-22 at 14 49 34" src="https://github.com/mekkablue/ShowItalic/assets/868987/e1d6b78f-5866-45c6-8ecf-74bc9a989951">

There is no issue the other way
<img width="619" alt="Screenshot 2024-04-22 at 14 49 44" src="https://github.com/mekkablue/ShowItalic/assets/868987/e60ec8fe-e421-497a-bb35-d70fe1427e57">

**Comment by mekkablue** [comment]
Fixed, thanks

**Comment by clauseggers** [comment]
Thank you.
